FROM node:latest
USER root

RUN apt-get update && \
    apt-get install -y vim
RUN git clone https://github.com/TitanLi/CloudNative.git
WORKDIR /CloudNative/kubernetes/API-Server
RUN npm install
RUN npm install -g pm2