---
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

tosca_definitions_version: tosca_simple_yaml_1_0

description: Make a pod using Kubernetes Synchronizer

imports:
  - custom_types/service.yaml
  - custom_types/serviceport.yaml
  - custom_types/trustdomain.yaml
  - custom_types/principal.yaml
  - custom_types/image.yaml
  - custom_types/site.yaml
  - custom_types/slice.yaml
  - custom_types/kubernetesservice.yaml
  - custom_types/kubernetesserviceinstance.yaml
  - custom_types/kubernetesconfigmap.yaml

topology_template:
  node_templates:
    default_trustdomain:
      type: tosca.nodes.TrustDomain
      properties:
        name: "default"
        must-exist: true

    my_config_map:
      type: tosca.nodes.KubernetesConfigMap
      properties:
        name: free5gc-configmap
        data: >
          {
            "free5gc.conf": "db_uri: mongodb://mongodb-svc/free5gc\nlogger:\n    file: /root/free5gc/install/var/log/free5gc/free5gc.log\n    trace: \n        app: 1\n        s1ap: 1\n        nas: 1\n        diameter: 1\n        gtp: 1\n        pfcp: 1\n        sbi: 1\nparameter:\n    no_ipv6: true\namf:\n    freeDiameter: amf.conf\n    s1ap:\n      addr: 192.188.2.2\n    gummei: \n      plmn_id:\n        mcc: 460\n        mnc: 99\n      mme_gid: 1\n      mme_code: 1\n    tai:\n      plmn_id:\n        mcc: 460\n        mnc: 99\n      tac: 1\n    security:\n        integrity_order : [ EIA1, EIA2, EIA0 ]\n        ciphering_order : [ EEA0, EEA1, EEA2 ]\n    network_name:\n        full: free5GC\nhss:\n    freeDiameter: hss.conf\npcrf:\n    freeDiameter: pcrf.conf\nsmf:\n    freeDiameter: smf.conf\n    pfcp:\n      - addr: 192.188.2.4\n    upf:\n      - addr: 192.188.2.5\n    http:\n      addr: 192.188.2.4\n      port: 8080\n    ue_pool:\n      - addr: 45.45.0.1/16\n    dns:\n      - 8.8.8.8\n      - 8.8.4.4\nupf:\n    pfcp:\n      addr:\n        - 192.188.2.5\n    gtpu:\n      - addr: 192.188.2.5\n    ue_pool:\n      - addr: 45.45.0.1/16\n    dns:\n      - 8.8.8.8\n      - 8.8.4.4"
          }
      requirements:
        - trust_domain:
            node: default_trustdomain
            relationship: tosca.relationships.BelongsToOne