apiVersion: v1
kind: Pod
metadata:
  name: stress-demo
spec:
  containers:
  - name: stress-demo-cpu
    image: polinux/stress
    resources:
      limits:
        cpu: "4"
        memory: "200Mi"
      requests:
        cpu: "4"
        memory: "100Mi"
    command: ["stress"]
    args: ["--cpu",  "4", "--timeout", "20"]