tosca_definitions_version: tosca_simple_yaml_1_0
 
description: Template for deploying a two-tier application servers on two
 
topology_template:
  inputs:
    # Admin user name and password to use with the WordPress application
    # omitted here for brevity
 
  node_templates:
    wordpress:
      type: tosca.nodes.WebApplication.WordPress
      properties:
        context_root: { get_input: context_root }
        admin_user: { get_input: wp_admin_username }
        admin_password: { get_input: wp_admin_password }
        db_host: { get_attribute: [ db_server, private_address ] }
      requirements:
      # The web application stack consists of the wordpress, the apache and the web_server node templates
        - host: apache
        - database_endpoint: wordpress_db
      interfaces:
        Standard:
          inputs:
            # get db_server private_address(IP Address)
            db_host: { get_attribute: [ db_server, private_address ] }
            db_port: { get_property: [ wordpress_db, port ] }
            db_name: { get_property: [ wordpress_db, name ] }
            db_user: { get_property: [ wordpress_db, user ] }
            db_password: { get_property: [ wordpress_sdb, password ] }  
 
    apache:
      type: tosca.nodes.WebServer.Apache
      properties:
        # omitted here for brevity
      requirements:
        - host: web_server
 
    web_server:
      type: tosca.nodes.Compute
      capabilities:
        # omitted here for brevity
 
    wordpress_db:
      type: tosca.nodes.Database.MySQL
      properties:
        name: { get_input: wp_db_name }
        user: { get_input: wp_db_user }
        password: { get_input: wp_db_password }
        port: { get_input: wp_db_port }
      requirements:
        - host: mysql
 
    mysql:
      type: tosca.nodes.DBMS.MySQL
      properties:
        root_password: { get_input: mysql_root_password }
        port: { get_input: mysql_port }
      requirements:
        - host: db_server
 
    db_server:
      type: tosca.nodes.Compute
      capabilities:
        # omitted here for brevity