apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
# 使用NodePort，表示使用Node上的實體Port提供對外訪問的能力
# 注意spec.ports.NodePort範圍限制預設為：30000~32767
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    name: frontend