apiVersion: v1
# 表示RC
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  # replicas 數量
  replicas: 1
  # RC的選擇器用來監控有這些Label的Pod
  selector:
    name: redis-master
  # RC根據template維持Pod數量
  template:
    metadata:
      # 指定Label標籤，必須對應到spec.selector
      labels:
        name: redis-master
    spec:
      containers:
      - name: master
        image: kubeguide/redis-master
        ports:
        - containerPort: 6379